### ISSUE TITLE
When you starting bro?

### ISSUE THREAD

**Issue by VivaanWadhwa** [apramm/ufc-betting-pred#1]
I have been waiting for a long time

**Comment by apramm** [comment]
exploring strategies to get appropriate data for the predictor, will start soon!

**Comment by VivaanWadhwa** [comment]
Really? Has been a long time since this repository got made 🤷🏻‍♂️

**Comment by kashish1928** [comment]
I’d like to circle back and ensure that the rollback is finalized on schedule so the product can be leveraged effectively.
